components:
  schemas:
    AbsensiRequest:
      type: object
      required:
        - tanggal_kehadiran
        - jam_kehadiran
        - jabatan
        - direktorat
      properties:
        tanggal_kehadiran:
          type: string
        jam_kehadiran:
          type: string
        jabatan:
          type: string
        direktorat:
          type: string

    Absensi:
      type: object
      properties:
        id:
          type: string
        nomor_induk_karyawan:
          type: string
        nama_karyawan:
          type: string
        jabatan:
          type: string
        direktorat:
          type: string

    SuccessResponseAbsensi:
      type: object
      properties:
        message:
          type: string
        data:
          $ref: "#/components/schemas/Absensi"

    SuccessResponseAbsensiList:
      type: object
      properties:
        message:
          type: string
        data:
          type: array
          items:
            $ref: "#/components/schemas/Absensi"

    SuccessResponseMessage:
      type: object
      properties:
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        message:
          oneOf:
            - type: string
            - type: array
              items:
                type: string
